name: pipeline-test


on:
  push:
    branches:
      - refactoring
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23' 

    - name: Build
      run: go build -o myapp ./cmd/app 

    - name: Start server
      run: ./myapp &

    - name: Wait for server to start
      run: sleep 5

    - name: Run tests
      run: go test ./tests


    - name: Stop server
      run: pkill myapp

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Run Docker container
      run: docker run -p 7540:7540 -d --name myapp_test myapp:latest

    - name: Wait for Docker container to start
      run: sleep 5

    - name: Test Docker container
      run: curl -f http://localhost:7540

    - name: Stop Docker container
      run: docker stop myapp_test 

    - name: Remove Docker container
      run: docker rm myapp_test